language: ruby
cache: bundler
rvm:
- 2.6
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external --empty-alt-ignore
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- chmod 600 /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: p85GKQYa76Z9Zrgt47SNaICzxKEOG5mt6SQcxq0zacogzjXvJi+e6hKv66N+jYEcjE6YINw0pSWbIswvvpDXJuk7qXN6BvdL1LiqerFgd1E5DYU2u9zPFsBDgUqw9o+tFWj4jK3QiTvhD8e7pONgZHiNrHey4APnxqEuvdAR1P2TjzBS0GGehN4eMuzDd9ZCxwKJsP5g2YYISZsfEJnTE/kzVuTumyDYyOrpfL1xfnEWDw+lD7tD6xPaRZRge+I+B1lK5OyyTJ7KY5Bb33dPNF0T0APGp9swwvZcdHpWKABTrmRYAlKmK0SK8Bhe0kuf0dPtA+K8Zxhj+sEIdgn8FZOOmIOUbbZ/QepSs37iAy3jtNwx3xpSGfyaCWYR2Zh7eVGQbedWlNm3gp50MGon+NW6y5+DXaUmGEUFZogwlAnf1sZMSqrTVR5rytsTUUbM4+tREPxNSgcstRamXau0rk5AMkVZB28yxzj6WWg32ryr7vMbuTkl9vpLJIJaoMSUGuc7gzag9YW4iPn1hbVp8TgiXktqcSKTkxHbbOUgL0s+t5U5Ui647/xd35unXR6mxhmu+W4slIHHFbM/igmgnrKCXQ1HSKk8XmE+1v1SSj2Eb6YgyKweQBey0kSdm+NHrMj54UvSMUBL8eP2HE+GI5Yzym2KfI7XV33hibKCXOc=
  - secure: XqkBBdcD1BQ2HN7ptpJCv1sxgkZ2o7dz3ufq+iuN8GyNl3ZEVonfpm1F3gLNW1n1uneamWMKrE8EAVkbAigKRl/Ebtj804RXSq+jWEP5V07yAlySzTGNct05X3GnVo01OKVzQV8G9w+ux5f1sEHSeOWhVKMVv20T6b7f6qOPFDB9VVCFKzCbvMhanqd5V/wN1Fqa3wSKnBIyi0imPmpYl6JWcjxLT0d4WtNW8B5dY1pZAzlGrydRCCVSepKAZbbsfeUfC7qKUgP1q/t7V3f7e8D5R0wdES7nZzYgyK5uU9F7dHkwNEdFnjQ/4mCbIculQn0/c5wANZKcQGL1auInbKUGn9xK2iHL1GmYDm5TyoBM4Sk35H+/GVjbb5UPu7GoIU1GrYnxmBd1FyxVjEC6rLlnHI1aoilBu9H2sKjwndSUys3/ABIMxbQxfSNyojIJNwUYA7QZsf9cBG6Q5k7N4terSSjfIFD+IealIsEl/VzY5GzbVhETcdwELpJ6H4sdXBxWdjbfSVjEgZz7xB0jgzKAjWaSCjDq7sudnQJciypyP69R54PK3tjGqrW6tXpwC5ZL7w+ha4PEBlpJc3zPE1YxaU9xFriGlW6dT0HodefS5WdkCTzWTyoqdsKKzUhdTM+AqVgK/Nk+kyLjNBJDCqiTzAtVaR8Dvc8SjxsRT6Y=
  - secure: rDwZLOpLIx55zrsjub/QBgfHZp39vsiyE+eXdPrZR8F2+lanAwDe+l1AGYviX0MuPkJmHoRCFxYq8u5nTfP5A6+DpaVWr2YIflRi50hBH3RZevJgx93vQdWv0DS3wrih2CMJSQXlE1GQvSw/owC1+MR9NVrKOaA3OXAIc7ZBZgIqGy7hUhBteKDsFcZF1Uh+TgpWj/Gy+Pr7CsPKog5V7uCsRXorUFH9+s4htHE/BYoMWh35IQ7Um87J2Xum+IsHQExu5JitoJ82yL/3biE7AMljEzUr1hY1ZnMCbOxPKLTM+EunbyU0eQ4LzkjdpMFQ95kkhBFFIbcJJemEuiRzfaS4mrXUOscNrOCiom21C9XOGRr2NoRNEmb8qEAvey1MVxhb9KEpleOnZy/3lVtCgyQApZD7eK12KXnKPxvPH/f/7CE6GGe2xuCKeimsC5czc3YWcKPc9UbWMmi1kFWDPMUloW/odrVuWjOrKiiVZTtPRAUfrF3cNQzTJyBpsaAEpfXo4hPBY5+g7rnKkCfGfOoqFl+OIF2D0fDHWOtZHHzfm5oa85QTiAwmjC4i2EdDknY+mfYeBjVQP0i6ncJ1UvahUqNXTvwUcPlVfCFs3+5fSoXeDk8ltkTQw1cNClbEXVac02VUIm0XRsEBQIT9jeMckwLahipEvWoEO5YFpas=
  - secure: d8WfTYttvGag38y6+aVSkzV2sRDXxl4qMttjp+ouiPB2Mae54mMUUD6NPEK0u8KSTHVEK3ltSU9G4FS1y0XtVfALr7I0AyesGvG0NKch8OSOO+yQr39bOa9m7XH6RsA8R7J4sCmXFVRon2+HgMg21GHT1N8VziQiWdh9Hp78M25G8BiLXnRBJu2pXThFQR2R3z5I0lkEIC58B0ZfwRy/lY1xeHI8sMXwhPn4KOMOxAbr5YnhMdjKT6UnEmYGK+L5iJ52cIu2Vd2qDEd+LOHUE/dRqm8XPexNx01LjPJeIfT8dSsoR5F4JT09bCv3tUwAlr7IUkQ4VkTWT0QFqzJ43s45WZy9zECjq1T8MlUuXFaSb24XtaHYHR0k5xQb3rUrP2yFAYkRfoln6VH7RA2CpSiMKTbhcQvVkPjAkWI0bRngHr24DA9uhBfZH2fOhweGCgh40nKpPgU7s1RdxYH8sFKR57NCW4vvgvgdr0FLvRdQfBqpQXA9BEfKlULDMnd46RJPXdOIPHY+2/bI3/I6huGLHMu2mKUbKXPhYNHH3YqysBYg7EnhvEc3f9OZolU3OzW+P7B2qZxerxpRmfm3+J/Os9xQtJ0kleMckVfsY+tRm0tl5Di97dzI/mH6DFgb/psqMkrsGU8L8Z6/zH+Mmy7hfdmcYCpltJ/xhxXraps=
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet -e 'ssh -p $DEPLOY_PORT' _site/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
    --delete-after
  on:
    branch: master
