# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            '(Insert Witticism here)'
tagline:          "Alan Fleming\u02BCs Web Pages"
description:      "Alan Fleming\u02BCs Web Pages"
url:              https://alanfleming.org
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

sidebar:
  alttext:           'Alan Fleming'
  img:            alanfleming.jpeg

# Defaults:  
defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      comments: false
      author: alan     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      comments: false
      show_meta: true
      autowarn: true   # Whether a warning banner should be applied after 3 years
      author: alan     # Default author for posts


# Pagination and Plugins
paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

permalink          : :year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  false   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
# Favico settings
favicon-32x32:                   'favicon-32x32.png'
android-icon-192x192:            'android-icon-192x192.png'
apple-icon-180x180:              'apple-icon-180x180.png'
apple-icon-152x152:              'apple-icon-152x152.png'
apple-icon-120x120:              'apple-icon-120x120.png'
apple-icon-precomposed:          'apple-icon-180x180.png'
msapplication_tileimage:         'android-icon-144x144.png'               
msapplication_tilecolor:         '#fabb00'

# Google Analytics ID
google_analytics:                 'UA-162227289-1'

# SEO
google_site_verification:  'i9c1V3OTcxZIP73j99BqwFJqQfqb8aUPZ78kQHWKs54'
bing_webmastertools_id:    '18690FCB9A81CEBACC28FB38C64D1553'
# yandex_site_verification:  ''
# alexa_verify_id:           ''
socialmedia:
  twitter: alanfleming

# Exclusions
exclude: [vendor, Gemfile, Gemfile.lock, LICENSE.md, README.md, deploy_rsa.enc] 

# Age before warning banner automatically applied (in round years)
warn_age: 3