# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Caveat', path: 'menu', url: 'caveat.html'}
- {name: 'Colophon', path: 'menu', url: 'colophon.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/alan-fleming'}
- {icon: 'twitter', link: 'https://twitter.com/alanfleming'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/alanfleming/'}
- {icon: 'envelope', link: 'mailto:af@alanfleming.org'}
# - {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
